name: JSON Validation

on:
  push:
    branches: [ "main", "production" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
            
